//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MapTool.rc
//
#define IDI_MAIN_ICON                   101
#define IDR_MAIN_ACCEL                  113
#define IDR_MENU                        141
#define IDD_WRK                         142
#define IDD_FLD                         143
#define IDD_LCL                         144
#define IDD_MTRL                        145
#define IDD_LIGHT                       146
#define IDD_FOG                         147
#define IDD_LAYER                       148
#define IDD_OBJ                         149
#define IDD_HELP                        150
#define IDB_WRK                         160
#define IDB_ICN01                       161
#define IDB_ICN02                       162
#define IDB_ICN03                       163
#define IDB_ICN04                       164
#define IDB_ICN21                       165
#define IDB_ICN22                       166
#define IDB_ICN23                       167
#define IDB_ICN24                       168
#define IDB_ICN25                       169
#define IDB_ICN26                       170
#define IDB_ICN27                       171
#define IDB_ICN28                       172
#define IDB_ICN29                       173
#define IDB_ICN30                       174
#define IDB_ICN31                       175
#define IDB_ICN32                       176
#define IDB_ICN33                       177
#define IDB_ICN34                       178
#define IDB_ICN35                       179
#define IDB_ICN36                       180
#define IDB_ICN37                       181
#define IDB_ICN38                       182
#define IDB_ICN39                       183
#define IDD_TOOL                        184
#define IDC_HELP_CLOSE                  1010
#define IDC_WRK_PANNEL                  1011
#define IDC_WRK_FLD_CRT                 1012
#define IDC_WRK_FLD_LOAD                1013
#define IDC_WRK_FLD_SAVE                1014
#define IDC_WRK_LCL_CRT                 1015
#define IDC_WRK_LCL_LOAD                1016
#define IDC_WRK_LCL_SAVE                1017
#define IDC_WRK_LCL_MOVE                1018
#define IDC_WRK_BT01                    1019
#define IDC_WRK_BT02                    1020
#define IDC_WRK_BT03                    1021
#define IDC_WRK_BT04                    1022
#define IDC_WRK_BT05                    1023
#define IDC_WRK_BT06                    1024
#define IDC_WRK_BT07                    1025
#define IDC_WRK_BT08                    1026
#define IDC_WRK_BT09                    1027
#define IDC_WRK_BT10                    1028
#define IDC_WRK_BT11                    1029
#define IDC_WRK_BT12                    1030
#define IDC_WRK_BT13                    1031
#define IDC_WRK_BT14                    1032
#define IDC_WRK_RNG                     1033
#define IDC_WRK_DH                      1034
#define IDC_WRK_AC                      1035
#define IDC_WRK_GRP                     1036
#define IDC_WRK_OBJ                     1037
#define IDC_WRK_LST                     1038
#define IDC_WRK_COL                     1039
#define IDC_WRK_COL_R                   1040
#define IDC_WRK_COL_G                   1041
#define IDC_WRK_COL_B                   1042
#define IDC_WRK_COL_ALL                 1043
#define IDC_FLD_NAME                    1055
#define IDC_FLD_NUM_X                   1056
#define IDC_FLD_NUM_Z                   1057
#define IDC_FLD_EXT                     1058
#define IDC_FLD_LCL_Y                   1059
#define IDC_FLD_LCL_N                   1060
#define IDC_FLD_LCL_NUM                 1061
#define IDC_FLD_LCL_WDT                 1062
#define IDC_FLD_LCL_UV                  1063
#define IDC_FLD_OK                      1064
#define IDC_FLD_CLOSE                   1065
#define IDC_LCL_NAME                    1070
#define IDC_LCL_NUM                     1071
#define IDC_LCL_WDT                     1072
#define IDC_LCL_UV                      1073
#define IDC_LCL_OK                      1074
#define IDC_LCL_CLOSE                   1075
#define IDC_LCL_POS_X                   1076
#define IDC_LCL_POS_Z                   1077
#define IDC_MTL_AL_C                    1101
#define IDC_MTL_AL_R                    1102
#define IDC_MTL_AL_G                    1103
#define IDC_MTL_AL_B                    1104
#define IDC_MTL_DF_C                    1105
#define IDC_MTL_DF_R                    1106
#define IDC_MTL_DF_G                    1107
#define IDC_MTL_DF_B                    1108
#define IDC_MTL_AM_C                    1109
#define IDC_MTL_AM_R                    1110
#define IDC_MTL_AM_G                    1111
#define IDC_MTL_AM_B                    1112
#define IDC_MTL_SP_C                    1113
#define IDC_MTL_SP_R                    1114
#define IDC_MTL_SP_G                    1115
#define IDC_MTL_SP_B                    1116
#define IDC_MTL_EM_C                    1117
#define IDC_MTL_EM_R                    1118
#define IDC_MTL_EM_G                    1119
#define IDC_MTL_EM_B                    1120
#define IDC_MTL_POW                     1121
#define IDC_MTL_OK                      1122
#define IDC_MTL_CLOSE                   1123
#define IDC_LGT_CMB                     1131
#define IDC_LGT_ADD                     1132
#define IDC_LGT_SUB                     1133
#define IDC_LGT_UP                      1134
#define IDC_LGT_TYP_P                   1135
#define IDC_LGT_TYP_S                   1136
#define IDC_LGT_TYP_D                   1137
#define IDC_LGT_DF_C                    1138
#define IDC_LGT_DF_R                    1139
#define IDC_LGT_DF_G                    1140
#define IDC_LGT_DF_B                    1141
#define IDC_LGT_AM_C                    1142
#define IDC_LGT_AM_R                    1143
#define IDC_LGT_AM_G                    1144
#define IDC_LGT_AM_B                    1145
#define IDC_LGT_SP_C                    1146
#define IDC_LGT_SP_R                    1147
#define IDC_LGT_SP_G                    1148
#define IDC_LGT_SP_B                    1149
#define IDC_LGT_POS_X                   1150
#define IDC_LGT_POS_Y                   1151
#define IDC_LGT_POS_Z                   1152
#define IDC_LGT_DIR_X                   1153
#define IDC_LGT_DIR_Y                   1154
#define IDC_LGT_DIR_Z                   1155
#define IDC_LGT_RNG                     1156
#define IDC_LGT_FAL                     1157
#define IDC_LGT_THT                     1158
#define IDC_LGT_PHI                     1159
#define IDC_LGT_AT0                     1160
#define IDC_LGT_AT1                     1161
#define IDC_LGT_AT2                     1162
#define IDC_LGT_OK                      1163
#define IDC_LGT_CLOSE                   1164
#define IDC_FOG_BGN                     1171
#define IDC_FOG_END                     1172
#define IDC_FOG_DNS                     1173
#define IDC_FOG_C                       1174
#define IDC_FOG_R                       1175
#define IDC_FOG_G                       1176
#define IDC_FOG_B                       1177
#define IDC_FOG_NONE                    1178
#define IDC_FOG_EXP                     1179
#define IDC_FOG_EXP2                    1180
#define IDC_FOG_LINE                    1181
#define IDC_FOG_OK                      1182
#define IDC_FOG_CLOSE                   1183
#define IDC_LYR_ORG                     1190
#define IDC_LYR_DST                     1191
#define IDC_LYR_OK                      1192
#define IDC_LYR_CLOSE                   1193
#define IDC_LYR_PANEL_ORG               1194
#define IDC_LYR_PANEL_DST               1195
#define IDC_LYR_ADD                     1196
#define IDC_LYR_DEL                     1197
#define IDC_OBJ_ID                      1201
#define IDC_OBJ_NAME                    1202
#define IDC_OBJ_R_X                     1203
#define IDC_OBJ_R_Y                     1204
#define IDC_OBJ_R_Z                     1205
#define IDC_OBJ_S_X                     1206
#define IDC_OBJ_S_Y                     1207
#define IDC_OBJ_S_Z                     1208
#define IDC_OBJ_T_X                     1209
#define IDC_OBJ_T_Y                     1210
#define IDC_OBJ_T_Z                     1211
#define IDC_OBJ_OK                      1212
#define IDC_OBJ_CLOSE                   1213
#define IDC_TOOL_NAME                   1220
#define IDC_TOOL_POS_X                  1221
#define IDC_TOOL_POS_Y                  1222
#define IDC_TOOL_POS_Z                  1223
#define IDC_TOOL_TILE_NUM               1224
#define IDC_TOOL_TILE_WDT               1225
#define IDC_TOOL_TILE_UV                1226
#define IDC_TOOL_TILE_OK                1227
#define IDC_TOOL_LYR_SRC0               1228
#define IDC_TOOL_LYR_SRC1               1229
#define IDC_TOOL_LYR_SRC2               1230
#define IDC_TOOL_LYR_SRC3               1231
#define IDC_TOOL_LYR_SRC4               1232
#define IDC_TOOL_LYR_SRC5               1233
#define IDC_TOOL_LYR_SRC6               1234
#define IDC_TOOL_LYR_SRC7               1235
#define IDC_TOOL_LYR_DST0               1236
#define IDC_TOOL_LYR_DST1               1237
#define IDC_TOOL_LYR_DST2               1238
#define IDC_TOOL_LYR_DST3               1239
#define IDC_TOOL_LYR_OK                 1240
#define IDC_TOOL_OBJ_ID                 1241
#define IDC_TOOL_OBJ_NAME               1242
#define IDC_TOOL_OBJ_R_X                1243
#define IDC_TOOL_OBJ_R_Y                1244
#define IDC_TOOL_OBJ_R_Z                1245
#define IDC_TOOL_OBJ_S_X                1246
#define IDC_TOOL_OBJ_S_Y                1247
#define IDC_TOOL_OBJ_S_Z                1248
#define IDC_TOOL_OBJ_T_X                1249
#define IDC_TOOL_OBJ_T_Y                1250
#define IDC_TOOL_OBJ_T_Z                1251
#define IDC_TOOL_OBJ_OK                 1252
#define IDM_CHANGEDEVICE                40002
#define IDM_TOGGLEFULLSCREEN            40003
#define IDM_EXIT                        40006
#define IDM_BACK                        40010
#define IDM_RETURN                      40011
#define IDM_RETURN_CTRL                 40012
#define IDM_TAB                         40013
#define IDM_TAB_BACK                    40014
#define IDM_RETURN_SHIFT                40015
#define IDM_NEW                         40016
#define IDM_OPEN                        40017
#define IDM_SAVE                        40018
#define IDM_ESC                         40019
#define IDM_SOLID                       40031
#define IDM_LGT                         40032
#define IDM_FOG                         40033
#define IDM_LINE_CAMERA                 40034
#define IDM_LINE_LOCAL                  40035
#define IDM_SHOW_FRAME                  40036
#define IDM_SHOW_SKY                    40037
#define IDM_SHOW_BNDBOX                 40038
#define IDM_CULLING_FRUSTUM             40039
#define IDM_HELP                        40040

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        185
#define _APS_NEXT_COMMAND_VALUE         40041
#define _APS_NEXT_CONTROL_VALUE         1255
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
